Fix incorrect missing keys error
SerializerMissingRequiredException: The following keys were missing from... errors were being triggered when a table field had NULL value.